In [52]:
import nltk
from nltk.corpus import stopwords
set(stopwords.words('english'))

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [53]:
from nltk.corpus import stopwords 

  
example_sent = "This is a sample sentence, showing off the stop words filtration."
  
#stop_words = set(stopwords.words('english')) 

#exam=BeautifulSoup(raw_words,"html.parser") #removing html tags
#letters=re.sub("[^a-zA-Z]"," ",exam.get_text()) #removing numbers and others except small and capital alphabets
low=example_sent.lower() #Converting everything to lower case
words=low.split() #spiliting sentences into words
    
useful= [w for w in words if not w in stopwords.words("english")] #removing stopping words 
use_sent= " ".join(useful)
print("Lower case: ",low)
print()
print("cleanned words: ",use_sent)
print()
perfect_words=[use_sent]
print()
print("Perfect words: ",perfect_words)
print()


Lower case:  this is a sample sentence, showing off the stop words filtration.

cleanned words:  sample sentence, showing stop words filtration.


Perfect words:  ['sample sentence, showing stop words filtration.']



In [13]:
l1=[1,2,3,5,6,7]
l2=[10,5,6,7,1,3]
for i in l1:
        if i not in l2:
            print(i)


2


In [25]:
filtered_sentence = []
for w in words:
    if not w in stopwords.words("english"):
        filtered_sentence.append(w)

In [26]:
filtered_sentence

['sample', 'sentence,', 'showing', 'stop', 'words', 'filtration.']

In [27]:
useful= [w for w in words if not w in stopwords.words("english")] #removing stopping words
useful

['sample', 'sentence,', 'showing', 'stop', 'words', 'filtration.']

In [28]:
words

['this',
 'is',
 'a',
 'sample',
 'sentence,',
 'showing',
 'off',
 'the',
 'stop',
 'words',
 'filtration.']

In [77]:
import io 
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
#word_tokenize accepts a string as an input, not a file. 
stop_words = set(stopwords.words('english')) 
file1 = open("paragraph.txt") 

'''line = file1.read()# Use this to read file content as a stream: 
line.encode('utf-8').strip()
words = line.split() 
for r in words: 
    if not r in stop_words: 
        appendFile = open('filteredtext.txt','a') 
        appendFile.write(" "+r) 
        appendFile.close() '''

'line = file1.read()# Use this to read file content as a stream: \nline.encode(\'utf-8\').strip()\nwords = line.split() \nfor r in words: \n    if not r in stop_words: \n        appendFile = open(\'filteredtext.txt\',\'a\') \n        appendFile.write(" "+r) \n        appendFile.close() '

In [78]:
with open("paragraph.txt", 'rb') as f:
  contents = f.read()
#contents = contents.rstrip("\n").decode("utf-16")
#contents = contents.split("\r\n")

In [81]:
tweet = file1.decode("utf8").encode('ascii','ignore')

AttributeError: '_io.TextIOWrapper' object has no attribute 'decode'

In [36]:
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
  
example_sent = "This is a sample sentence, showing off the stop words is  filtration. and sample sample sample showing the the "
  
stop_words = set(stopwords.words('english')) 
  
word_tokens = word_tokenize(example_sent) 
  
filtered_sentence = [w for w in word_tokens if not w in stop_words] 
  
filtered_sentence = [] 
  
for w in word_tokens: 
    if w not in stop_words: 
        filtered_sentence.append(w) 
  
print(word_tokens) 
print(filtered_sentence)

['This', 'is', 'a', 'sample', 'sentence', ',', 'showing', 'off', 'the', 'stop', 'words', 'is', 'filtration', '.', 'and', 'sample', 'sample', 'sample', 'showing', 'the', 'the']
['This', 'sample', 'sentence', ',', 'showing', 'stop', 'words', 'filtration', '.', 'sample', 'sample', 'sample', 'showing']


[nltk_data] Downloading package punkt to /home/sands/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [37]:
from sklearn.feature_extraction.text import CountVectorizer

In [47]:
vect=CountVectorizer(min_df=2,ngram_range=(1,2)).fit(word_tokens) #words converting into vectors , minimum document frequency min_df=5
print(vect)
print (len(vect.get_feature_names()))

#X_train_vetorised=vect.transform(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=2,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)
4


In [49]:
vetorised=vect.transform(word_tokens)
print(vetorised)

  (1, 0)	1
  (3, 1)	1
  (6, 2)	1
  (8, 3)	1
  (11, 0)	1
  (15, 1)	1
  (16, 1)	1
  (17, 1)	1
  (18, 2)	1
  (19, 3)	1
  (20, 3)	1


In [44]:
vetorised.shape

(21, 4)

In [45]:
vetorised.size

11

In [50]:
vetorised=vect.transform(word_tokens).toarray()
print(vetorised)

[[0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 1]]
